exports.STATUS = {
    ON: 'ON',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
}

exports.TYPES = {
    AUTH: 'AUTH',
    CHANNEL: 'CHANNEL',
    MESSAGE: 'MESSAGE',
    EMOTICON: 'EMOTICON',
    TYPING: 'TYPING',
}

exports.METHODS = {
    CREATE: 'CREATE',
    READ: 'READ',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    READ_BY_CHANNEL_ID: "READ_BY_CHANNEL_ID",
    READ_BY_PARENT_ID: "READ_BY_PARENT_ID",
    READ_BY_USER_ID: "READ_BY_USER_ID",
}
